name: compile-sketches

on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ESP32 platform dependencies
        run: pip3 install pyserial

      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          cli-compile-flags: |
            - "--build-property 'compiler.cpp.extra_flags=-Wno-error'"
          fqbn: "esp32:esp32:esp32"
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          libraries: |
            - name: StreamDebugger
            - source-path: ./
          sketch-paths: |
            - examples